update version-management action

diff --git a/.github/actions/version-management/action.yml b/.github/actions/version-management/action.yml
--- a/.github/actions/version-management/action.yml
+++ b/.github/actions/version-management/action.yml
@@ -49,10 +49,10 @@ runs:
       id: get_current_version
       shell: bash
       run: |
-        # if ! grep -q '^version: [0-9]\+\.[0-9]\+\.[0-9]\++[0-9]\+$' ${{ inputs.pubspec_path }}; then
-        #   echo "::error::Invalid or missing version in ${{ inputs.pubspec_path }}. Expected format: x.y.z+build"
-        #   exit 1
-        # fi
+        if ! grep -q '^version: [0-9]\+\.[0-9]\+\.[0-9]\+\(-RC\)\?\+[0-9]\+$' ${{ inputs.pubspec_path }}; then
+          echo "::error::Invalid or missing version in ${{ inputs.pubspec_path }}. Expected format: x.y.z+build or x.y.z-RC+build"
+          exit 1
+        fi
         current_version=$(grep 'version:' ${{ inputs.pubspec_path }} | sed 's/version: //')
         echo "current_version=$current_version" >> $GITHUB_OUTPUT
         echo "Current version: $current_version"
@@ -92,8 +92,8 @@ runs:
           build_number=$(echo "$current_version" | cut -d'+' -f2)
           
           # Validate version format
-          if ! echo "$version_part" | grep -q '^[0-9]\+\.[0-9]\+\.[0-9]\+$'; then
-            echo "::error::Invalid version format in pubspec.yaml: $version_part. Expected: x.y.z"
+          if ! echo "$version_part" | grep -q '^[0-9]\+\.[0-9]\+\.[0-9]\+\(-RC\)\?$'; then
+            echo "::error::Invalid version format in pubspec.yaml: $version_part. Expected: x.y.z or x.y.z-RC"
             exit 1
           fi
           
