revert check

diff --git a/.github/actions/version-management/action.yml b/.github/actions/version-management/action.yml
--- a/.github/actions/version-management/action.yml
+++ b/.github/actions/version-management/action.yml
@@ -49,10 +49,10 @@ runs:
       id: get_current_version
       shell: bash
       run: |
-        if ! grep -q '^version: [0-9]\+\.[0-9]\+\.[0-9]\++[0-9]\+$' ${{ inputs.pubspec_path }}; then
-          echo "::error::Invalid or missing version in ${{ inputs.pubspec_path }}. Expected format: x.y.z+build"
-          exit 1
-        fi
+        # if ! grep -q '^version: [0-9]\+\.[0-9]\+\.[0-9]\++[0-9]\+$' ${{ inputs.pubspec_path }}; then
+        #   echo "::error::Invalid or missing version in ${{ inputs.pubspec_path }}. Expected format: x.y.z+build"
+        #   exit 1
+        # fi
         current_version=$(grep 'version:' ${{ inputs.pubspec_path }} | sed 's/version: //')
         echo "current_version=$current_version" >> $GITHUB_OUTPUT
         echo "Current version: $current_version"
