test the use of tags for race conditions

diff --git a/.github/actions/version-bump/action.yml b/.github/actions/version-bump/action.yml
--- a/.github/actions/version-bump/action.yml
+++ b/.github/actions/version-bump/action.yml
@@ -34,13 +34,14 @@ runs:
           && sudo apt update \
           && sudo apt install gh -y
 
-    # - name: Set up Git
-    #   shell: bash
-    #   run: |
-    #     git config user.name "github-actions[bot]"
-    #     git config user.email "github-actions[bot]@users.noreply.github.com"
+    - name: Set up Git
+      shell: bash
+      run: |
+        git config user.name "github-actions[bot]"
+        git config user.email "github-actions[bot]@users.noreply.github.com"
+        # git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ZanderCowboy/multichoice.git
 
-    - name: Run version bump script
+    - name: Run version bump logic
       shell: bash
       env:
         GITHUB_TOKEN: ${{ inputs.github-token }}
@@ -63,14 +64,16 @@ runs:
 
         echo "Bump type identified: $BUMP_TYPE"
 
-        CURRENT_VERSION=$(grep '^version:' $VERSION_FILE | sed 's/version: //')
-        echo "Current version: $CURRENT_VERSION"
+        git fetch --tags
+        LATEST_TAG=$(git tag --sort=-version:refname 'v*.*.*' | head -n1)
+        if [ -z "$LATEST_TAG" ]; then
+          echo "Error: No tags found in the repository."
+          exit 1
+        fi
+        echo "Latest tag: $LATEST_TAG"
 
-        SEMVER=$(echo "$CURRENT_VERSION" | cut -d '+' -f 1)
-        echo "Semantic version: $SEMVER"
-        BUILD_NUM=$(echo "$CURRENT_VERSION" | cut -d '+' -f 2)
-        echo "Build number: $BUILD_NUM"
-
+        SEMVER=${LATEST_TAG#v}
+        echo "Current version: $SEMVER"
         MAJOR=$(echo "$SEMVER" | cut -d '.' -f 1)
         MINOR=$(echo "$SEMVER" | cut -d '.' -f 2)
         PATCH=$(echo "$SEMVER" | cut -d '.' -f 3)
@@ -90,14 +93,18 @@ runs:
             ;;
         esac
 
-        echo "Old build number: $BUILD_NUM"
-        BUILD_NUM=$(echo "$BUILD_NUM" | tr -d '\r\n[:space:]')
-        BUILD_NUM=$((BUILD_NUM + 1))
-        echo "Build number incremented to: $BUILD_NUM"
+        NEW_SEMVER="$MAJOR.$MINOR.$PATCH"
+        echo "New version: $NEW_SEMVER"
+        NEW_VERSION="${NEW_SEMVER}+${{ github.run_number }}"
+        echo "New version with build number: $NEW_VERSION"
 
-        NEW_VERSION="$MAJOR.$MINOR.$PATCH+$BUILD_NUM"
-        echo "New version: $NEW_VERSION"
+        sed -i -E "s/^version:.*/version: $NEW_VERSION/" "${{ inputs.version-file }}"
+
+        git add "${{ inputs.version-file }}"
+        git commit -m "chore: bump version to $NEW_VERSION"
+        git push origin HEAD
+
+        git tag "v${NEW_SEMVER}"
+        git push origin "v${NEW_SEMVER}"
+
         echo "new-version=$NEW_VERSION" >> "$GITHUB_OUTPUT"
-        echo "new-version=$NEW_VERSION" >> "$GITHUB_ENV"
-
-        sed -i -E "s/^(version:[[:space:]]*).*/\1$NEW_VERSION/" $VERSION_FILE
